services:
  - type: web
    name: alomana-app
    env: python
    plan: free
    buildCommand: python -m pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_DEFAULT_USERNAME
        value: admin
      - key: ADMIN_DEFAULT_PASSWORD
        value: admin123
      - key: USER_DEFAULT_USERNAME
        value: usuario_demo
      - key: USER_DEFAULT_EMAIL
        value: usuario@alomana.local
      - key: USER_DEFAULT_PASSWORD
        value: usuario123
